// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJogg406igo09620LBp4gVvSt2ijlv410',
    appId: '1:170137595379:android:58ba56e93141e1d6b23686',
    messagingSenderId: '170137595379',
    projectId: 'evento-linkdev',
    databaseURL: 'https://evento-linkdev-default-rtdb.firebaseio.com',
    storageBucket: 'evento-linkdev.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQVVkmig1QL3sDmMLsGgeKDLY2hau_0M',
    appId: '1:170137595379:web:457297f7e0478579b23686',
    messagingSenderId: '170137595379',
    projectId: 'evento-linkdev',
    authDomain: 'evento-linkdev.firebaseapp.com',
    databaseURL: 'https://evento-linkdev-default-rtdb.firebaseio.com',
    storageBucket: 'evento-linkdev.appspot.com',
    measurementId: 'G-2Y2N56E203',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-T2uvRixjhFb-kyZqrw3qQqjvNc00BFc',
    appId: '1:170137595379:ios:139ee4680eb511dcb23686',
    messagingSenderId: '170137595379',
    projectId: 'evento-linkdev',
    databaseURL: 'https://evento-linkdev-default-rtdb.firebaseio.com',
    storageBucket: 'evento-linkdev.appspot.com',
    iosBundleId: 'com.example.eventoApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-T2uvRixjhFb-kyZqrw3qQqjvNc00BFc',
    appId: '1:170137595379:ios:139ee4680eb511dcb23686',
    messagingSenderId: '170137595379',
    projectId: 'evento-linkdev',
    databaseURL: 'https://evento-linkdev-default-rtdb.firebaseio.com',
    storageBucket: 'evento-linkdev.appspot.com',
    iosBundleId: 'com.example.eventoApp',
  );

}